### PR TITLE
refactor: renaming renaming renaming renaming renaming renaming renaming renaming renaming renaming renaming

### LINKED ISSUE #25: Class2307 is ChatFormatting
It is the chat formatting class for color codes.

### PR DESCRIPTION
**Pull request by DataM0del**
Fixes #25

### CODE REVIEW

**Comment by StormingMoon** [comment]
Nice this will be merged btw can u look into the singleplayer issue? its so weird i legitametly cant figure it out

**Comment by DataM0del** [comment]
> btw can u look into the singleplayer issue? its so weird i legitametly cant figure it out


Currently I can't even get it to compile as I didn't give it enough memory, I've just gave it 1 GB so hopefully it will work now

**Comment by DataM0del** [comment]
image
It compiled!
Also, I set it to 1 GB and it works.

**Comment by StormingMoon** [comment]
The singleplayer things leaves like no errors when it hangs so like tracking it down is a pain in the ass we tried a million breakpoints and prints to debug we got a little further but it still seems to fuck up something with the integrated server seems like

**Comment by DataM0del** [comment]
I have the jar now.

image

**Comment by DataM0del** [comment]
image

**Comment by StormingMoon** [comment]
wanna join the org

**Comment by DataM0del** [comment]
I just noticed that the jar was empty because it created a JAR file that had the size of 0 bytes

**Comment by StormingMoon** [comment]
we have a private discord add me .stormingmoon

**Review by MarkGG8181 — APPROVED** [review]
decompilation 🤪

**Comment by AppuCodes** [comment]
> The singleplayer things leaves like no errors when it hangs so like tracking it down is a pain in the ass we tried a million breakpoints and prints to debug we got a little further but it still seems to fuck up something with the integrated server seems like

Just copy these classes from Minecraft 1.16.4, I doubt Sigma changed them (or compare and contrast)

**Pull request merged**
